### ISSUE TITLE
Scrolling doesn't sync

### ISSUE THREAD

**Issue by kdzwinel** [BrowserSync/browser-sync-client#16]
Scrolling doesn't seem to be working. IMO the issue hides it these two lines:

https://github.com/shakyShane/browser-sync-client/blob/master/lib/ghostmode.scroll.js#L72 - here we are sending `{x:num, y:num}` in `raw` property (my guess is that only `y` was ment to be sent).

https://github.com/shakyShane/browser-sync-client/blob/master/lib/ghostmode.scroll.js#L41- and here we are trying to call `window.scrollTo(0, {x:num, y:num})`.

**Comment by faceyspacey** [comment]
funny seeing you here @kdzwinel lol...I'm looking to easily abstract out just the "interaction sync" aspects out of Browser Sync, but it seems to be coupled to the rest of what `bs` does. I dont suppose you have an idea how to best do that or if there are other packages geared just to "interaction sync"? Might be able to help you too since you've been waiting for this issue to be fixed for almost a year.

**Comment by shakyShane** [comment]
@faceyspacey this is not a bug that needs fixing for 99% of our users

@kdzwinel If you could provide a small project that highlights your issue we would happily look at it :)

**Comment by kdzwinel** [comment]
@shakyShane I did what I should have done it he first place and created a PR ;) 

@faceyspacey hey again! Ping me on gmail (this task is not the best place to discuss it), I may have some hints for you.
